---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service }}  
spec:
  selector: {{- .Values.selector | toYaml | trim | nindent 4 }}
  ports:
  - name: blockmanager
    protocol: TCP
    port: {{ .Values.blockmanager.port }}
    targetPort: {{ .Values.blockmanager.port }}
  - name: driver
    protocol: TCP
    port: {{ .Values.driver.port }}
    targetPort: {{ .Values.driver.port }}
  - name: spark-ui
    protocol: TCP
    port: {{ .Values.spark_ui.port }}
    targetPort: {{ .Values.spark_ui.port }}