apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spark-ui
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.url }} 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.service }}  
            port:
              number: {{ .Values.spark_ui.port }}