---
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-configuration-job
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 60
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kcadm
        image: "quay.io/keycloak/keycloak:{{ .Values.keycloak.version }}"
        env:
        - name: KEYCLOAK_ADMIN_USER
          value: "{{ .Values.keycloak.user }}"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "{{ .Values.keycloak.password }}"
        command: ["/scripts/configure.sh"]
        volumeMounts:
        - name: config
          mountPath: /config
        - name: scripts
          mountPath: /scripts
      volumes:
      - name: config
        configMap:
          name: clients
      - name: scripts
        configMap:
          name: scripts
          defaultMode: 0050